added google report
Studio-Yandex-Practicum-Hackathons/culture_its_ok_1 pull request #21
Opened 2023-08-14 09:46 UTC by SergeychUK92

Написал класс формирующий отчеты в Google Spreadsheets;

2023-08-16 22:54 UTC, kr0t commented on services/google_report.py
> +        return self
А для чего ты везде возвращаешь ссылку на экземпляр класса ( `self` )? Это выглядит не идиоматично для Python и должно работать без этого.

2023-08-19 23:22 UTC, dcomrad requested changes

2023-08-19 23:22 UTC, dcomrad commented on services/google_report.py
> +    def add_headers(self, *args):
Принимай двумерный массив, где каждый элемент, это отображение ячейки таблицы. Шапка отчёта может быть многострочной. И пусть метод будет называться в единственном числе add_header и при вызове не добавлять данные для шапки отчёта, а переписывать их.

2023-08-19 23:22 UTC, dcomrad commented on services/google_report.py
> +        service.spreadsheets().create(body=spreadsheet_body)
Замечания общего характера:
- нужны docstrings для класса и его методов
- нужны аннотации типов

Перед созданием ПР, протестируй работу кода. Нужно понимать, для кого и чего он требуется и убедиться, что он решает поставленную задачу.

Сделай так, чтобы я, как посльзователь твоего класса мог сделать такое

```
google_info = ...

header = [
    ['Отчёт по использованию бота'],
    ['Маршрут:', 'Маршрут 1'],
    ['Количество пользователей, воспользовавшихся ботом:', *[''] * 3, 50],
    ['из них'],
    ['прошли маршрут целиком', *[''] * 3, 40],
]

object1 = [
    ['Объект 1'],
    ['Пользователь', 'Вопрос', 'Ответ'],
    ['Александр', 'Что думаете?', 'Выглядит не очень']
]

object2 = [
    ['Объект 2'],
    ['Пользователь', 'Вопрос', 'Ответ'],
    ['Пётр', 'Как вы думаете, что это?', 'Титаник']
]

report = GoogleReport(google_info)
report.add_title('Заголовок')
report.add_header(header)
report.add_rows(object1)
report.add_rows(object2)
report_url = report.create() # д.б. ссылка, перейдя по которой откроется созданная таблица
```
и перейдя по ссылке увидел отчёт

2023-08-21 16:00 UTC, SergeychUK92 commented on services/google_report.py
> +    def add_rows(self, num):
Понял, что функция add_headers создает шапку таблицы.

2023-08-24 12:05 UTC, merged